### ISSUE TITLE
Avro decodes int8 tiles as uint8

### ISSUE THREAD

**Issue by lossyrob** [locationtech-labs/geopyspark#199]
Should check ushort/short as well.

**Comment by jbouffard** [comment]
This issue is going to be tricky to solve due to how we encode/decode `MultibandTile`s. In order to decode the `Tile` to the right type of numpy array, we need its `CellType`. However, this information is not available in the `MultibandTile`'s schema as it's just a union of all possible `Tile` schemas. To solve this problem, we'll somehow have to keep track of the `CellType` as it goes back and forth between scala and python.

It might be good to have an additional field in the `Tile` schema that contains the name of the `CellType`. This way, it will still be obtainable even if it's in a `MultibandTile`.

**Comment by jbouffard** [comment]
Resolved in #245
