### ISSUE TITLE
NoData values are not ending up in numpy array correctly

### ISSUE THREAD

**Issue by lossyrob** [locationtech-labs/geopyspark#320]
<img width="920" alt="screen shot 2017-07-05 at 1 42 43 pm" src="https://user-images.githubusercontent.com/2320142/27877254-efe6a480-6187-11e7-8704-cff9f8feee50.png">

In this example, I have the chatta_rdd, which is defined as

```python
MAX_ZOOM = 12
query_rdd = catalog.query(
    pysc, LayerType.SPATIAL, 
    "s3://azavea-datahub/catalog", nlcd_layer_name, 
    MAX_ZOOM, query_geom=chatta_poly)

chatta_rdd = query_rdd.convert_data_type("int8").cache()
```

When I mask it, and get a numpy array out of it, the nodata values (masked values) are set to 0. However based on the nodata they should be set to -128, correct?

**Comment by jbouffard** [comment]
Where is it returning 0? In the actual `Tile` itself? Because the `no_data_value` of both those `Tile`s is -128.

**Comment by echeipesh** [comment]
The correct metadata for the layer is `0`:

```
scala> store.readMetadata[TileLayerMetadata[SpatialKey]](LayerId("nlcd-tms-epsg3857", 5)).cellType
res1: geotrellis.raster.CellType = int8ud0
```
So it looks like a problem with CellType decoding

**Comment by jbouffard** [comment]
Oh, sorry. I misread the issue.

What I believe is happening here is that `no_data_value` was ever set when using `convert_data_type`
https://github.com/locationtech-labs/geopyspark/blob/master/geopyspark/geotrellis/layer.py#L525

If that isn't set, then it just uses whatever the default `NoData` value for that `CellType`.

**Comment by jbouffard** [comment]
My previous comment was wrong. I thought you were having issues with the `mask` operation, but I now realize the problem is endemic throughout GeoPySpark. The issue lies with how ProtoBuf encodes the cell values for certain data types. Because ProtoBuf can't store any numeric value smaller than `int32`, those types that are too small need to be stored as `int32`. By doing this, though, some of the values within the tiles are changed to meet the encoded type, namely the no data values.

For example, encoding a `ShortArrayTile` in Scala:

```scala
scala> val tile = ShortArrayTile(Array[Short](1, Short.MinValue, 0, 5), 2, 2)
tile: geotrellis.raster.ShortArrayTile = ShortConstantNoDataArrayTile([S@27c7618,2,2)

scala> implicitly[ProtoBufCodec[Tile, ProtoTile]].encode(tile)
res7: protos.tileMessages.ProtoTile =
cols: 2
rows: 2
cellType {
  dataType: SHORT
  nd: -32768.0
  hasNoData: true
}
sint32Cells: 1
sint32Cells: -2147483648
sint32Cells: 0
sint32Cells: 5
```

Even though `nd` is set to `Short.MinValue` the resulting encoded cell has a value of -2147483648, or `Int.MinValue`.


This also appears to be the case with unsigned data types:

```scala
scala> val tile2 = UByteArrayTile(Array[Byte](1, 1, 1, -10, -10, -10), 2, 3).withNoData(Some(-10))
tile2: geotrellis.raster.Tile = UByteUserDefinedNoDataArrayTile([B@46aa32bb,2,3,uint8ud246)

scala> implicitly[ProtoBufCodec[Tile, ProtoTile]].encode(tile2)
res8: protos.tileMessages.ProtoTile =
cols: 2
rows: 3
cellType {
  dataType: UBYTE
  nd: -10.0
  hasNoData: true
}
uint32Cells: 1
uint32Cells: 1
uint32Cells: 1
uint32Cells: 2147483648
uint32Cells: 2147483648
uint32Cells: 2147483648
```

As with the previous example, all `nd`s are converted. In this case, they a changed to `Int.MaxValue` instead. This also shows that this same issue arises from user defined, no data values.

Unfortunately, the problem is carried over during decoding as well.

```scala
scala> val encoded = implicitly[ProtoBufCodec[Tile, ProtoTile]].encode(tile2)
encoded: protos.tileMessages.ProtoTile =
cols: 2
rows: 3
cellType {
  dataType: UBYTE
  nd: -10.0
  hasNoData: true
}
uint32Cells: 1
uint32Cells: 1
uint32Cells: 1
uint32Cells: 2147483648
uint32Cells: 2147483648
uint32Cells: 2147483648

scala> implicitly[ProtoBufCodec[Tile, ProtoTile]].decode(encoded).toArray
res11: Array[Int] = Array(1, 1, 1, -2147483648, -2147483648, -2147483648)
```

This problem is only affecting `bit`, `byte`, 'ubyte`, `short`, and `ushort` tiles. One solution could be to simply map over these arrays and replace the wrong no data values with the correct ones. Please let me know if there's another solution we could try.
