### ISSUE TITLE
Upgrading To GeoTrellis 1.1.0-SNAPSHOT Breaks Tests

### ISSUE THREAD

**Issue by jamesmcclain** [locationtech-labs/geopyspark#79]
... but that upgrade is required for certain functionality, viz. ingests.  This suggests that we may be lacking in test coverage of the ingest functionality.

![screenshot from 2017-03-28 22 07 50](https://cloud.githubusercontent.com/assets/11281373/24435450/6a659f68-1403-11e7-8bbe-283210a82d7b.png)

**Comment by jbouffard** [comment]
There looks like there's two failing tests: [ProjectedExtent](https://travis-ci.org/locationtech-labs/geopyspark/jobs/216177531#L4870) and [TemporalProjectedExtent](https://travis-ci.org/locationtech-labs/geopyspark/jobs/216177531#L4874). I believe this is due to changes in how these two types are encoded/decoded by the `AvroEncoder`. I'll look into this further to make sure, though,

**Comment by jamesmcclain** [comment]
Okay, sounds good.

**Comment by jamesmcclain** [comment]
Fixed by locationtech-labs/geopyspark#80
